### ISSUE TITLE
add baseurl support

### ISSUE THREAD

**Issue by mklabs** [mklabs/h5bp-docs#4]
generated website may or may not be accessible from the server root,  and often runs under some context path like `/docs/` or `/wiki/`

--baseurl flag and options would allow that. Both used when starting up the local test server (when `--server`flag is used) and generating each page individually.

allow the href to be something like `/docs/Page-Name/` and assets `/docs/css/style.css`.

**Comment by nimbupani** [comment]
perfect, this is what I wanted :)

**Comment by mklabs** [comment]
Nice :) Landed in 2b1b15d1cd720d37ef91da44e0086c1356e0ed4a
