### ISSUE TITLE
generate --template broken 

### ISSUE THREAD

**Issue by ymazzer** [mklabs/h5bp-docs#9]
In next branch, within the Generator class, you had :

``` javascript
//...
o.layout = o.layout || o.template;
//...
```

So that o.layout was defined if a template was given as argument to the generate script. In [this revision](https://github.com/mklabs/h5bp-docs/blob/9877e4bcad7405a7c11b5f0f253470dadae6f99f/main.js) this line was replaced by :

``` javascript
//...
o.layout = o.layout;
//...
```

As a consequence of this change, the --template argument does not work as expected since it goes in the conditional block which adds `/index.html`.

**Comment by mklabs** [comment]
Hey @ymazzer 

Thanks for the feedback. Sounds like you found the bug. Would you like to send a patch?

The [two-tree lines here](https://github.com/mklabs/h5bp-docs/blob/9877e4bcad7405a7c11b5f0f253470dadae6f99f/main.js#L40-43) are related. As far as I can remember, I did this while creating a custom [grunt task for generating doc](https://github.com/h5bp/node-build-script/blob/docs/grunt.js#L55-118).

Maybe, I was just drunk cause I don't see now why I did this :/

**Comment by ymazzer** [comment]
I planned to send you a pull request but didn't have time to work on it by now. As soon as I get 5 minutes to work on it I will fix it. 
Shouldn't local bear instance be installed after the work not before ;)

**Comment by mklabs** [comment]
no problem Yannis, there's no hurry.
